const assert=require('node:assert/strict'),fs=require('node:fs'),vm=require('node:vm');
const html=fs.readFileSync(new URL('../index.html','file://'+__filename),'utf8');
const parser=html.split('// START CLAUDE STREAM PARSER')[1].split('// END CLAUDE STREAM PARSER')[0].split('\n').slice(1).join('\n');
const context=vm.createContext({});vm.runInContext(parser,context);const parse=context.claudeStreamSnapshot;
const old=['❯ 이전 질문','● 이전 답변','❯'];
assert.equal(parse(old,'새 질문'),null,'must not replay the previous response');
const partial=[...old,'❯ 새 질문','● 지금 답변이','  이어지는 중입니다.','✻ Thinking… (esc to interrupt)','❯'];
assert.equal(parse(partial,'새 질문').text,'지금 답변이\n이어지는 중입니다.');
assert.equal(parse(partial,'새 질문').idle,false,'empty input prompt during generation is not completion');
const final=[...old,'❯ 새 질문','● 한국어 답변입니다.','', '  두 번째 문단입니다.','✻ Brewed for 3s · done 8:08 PM','──────','❯','auto mode on'];
assert.equal(parse(final,'새 질문').idle,true);
assert.equal(parse(final,'새 질문').text,'한국어 답변입니다.\n\n두 번째 문단입니다.');
const tool=[...old,'❯ 새 질문','● Bash(pwd)','  ⎿  /secret/tool/output','✻ Working…','❯'];
assert.equal(parse(tool,'새 질문').text,'','tools and tool output must not become an assistant reply');
assert.equal(parse(tool,'새 질문').status,'도구를 실행하고 있어요');
const afterTool=[...tool.slice(0,-2),'● 도구 결과를 정리합니다.','  답변 내용입니다.','❯'];
assert.equal(parse(afterTool,'새 질문').text,'도구 결과를 정리합니다.\n답변 내용입니다.');
const repeated=['❯ 같은 질문','● 오래된 응답','❯'];
assert.equal(parse(repeated,'같은 질문',1),null,'a repeated prompt must wait for a new echo');
assert.equal(parse([...repeated,'❯ 같은 질문','● 새로운 응답','❯'],'같은 질문',1).text,'새로운 응답');
assert.equal(parse(['❯ 공백이  있는 질문','● 정상','❯'],'공백이 있는 질문').text,'정상');
assert.equal(parse(['❯ 새 질문','● 본문','  ● 목록 안의 점','❯'],'새 질문').text,'본문\n● 목록 안의 점');
for(const [,source] of html.matchAll(/<script(?: [^>]*)?>([\s\S]*?)<\/script>/g)){if(source.trim())new vm.Script(source)}
assert.equal(parse([...partial.slice(0,-1),...Array.from({length:18},(_,i)=>'  본문 '+i),'✻ Brewed for 3s · done','────','❯'],'새 질문').idle,true,'old spinner scrollback must not leave a completed reply waiting');
assert.equal(parse([...partial,...Array(40).fill('')],'새 질문').idle,false,'blank terminal padding must not hide a busy spinner');
assert.equal(parse(['❯ 새 질문','● 첫 답변입니다.','● Bash(pwd)','  ⎿ 결과','● 두 번째 답변입니다.','✻ Working…','❯'],'새 질문').blocks.length,2,'tool boundaries must retain both answer blocks');
assert.equal(parse(['❯ 새 질문','● 정상 답변','● Bash','❯'],'새 질문').blocks.length,1,'a tool label being painted must not create a false answer');
assert.equal(parse(['❯ 새 질문','● 정상 답변','  Bash(pwd)','❯'],'새 질문').text,'정상 답변','repainting tool commands must not be appended to prose');
console.log('Stream parser regressions and inline JavaScript syntax OK.');
